name: Semi-auto trigger

on:
  issue_comment:
    types: [created]

jobs:
  echo-true:
    if: ${{ github.event.comment.user.login == 'faizul118' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: echo true
      run: echo true > README.md

    - name: Commit and push status true
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Set status to true"
        git push --force

  wait-15mins:
    runs-on: ubuntu-latest
    needs: echo-true

    steps:

    - name: Wait for 15 minutes
      run: sleep 180

  echo-false:
    runs-on: ubuntu-latest
    needs: wait-15mins

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: echo false
      run: |
        git pull
        echo false > README.md

    - name: Revert to false
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Revert to false"
        git push --force
