name: Semi-auto trigger

on:
  issue_comment:
    types: [created]

jobs:
  echo true:
    if: ${{ github.event.comment.user.login == 'faizul118' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: echo true
      run: echo true > status.txt

    - name: Commit and push status true
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add status.txt
        git commit -m "Set status to true"
        git push

  Wait 15 minutes:
    - name: Wait for 15 minutes
      run: sleep 180

  echo false:
    - name: echo false
      run: echo false > status.txt

    - name: Revert to false
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add status.txt
        git commit -m "Revert to false"
        git push
