name: Set IsRunning = false

on:
  push:
    paths:
      - status.txt

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update status.txt
        run: echo "false" > status.txt

      - name: Revert to false
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add status.txt
          git commit -m "Revert to false"
          git push
